### ISSUE TITLE
Issue on 3.779 and 1.1.2 (stable)

### ISSUE THREAD

**Issue by maxdd** [patrickkfkan/volumio-ytcr#19]
Hello,
i guess you are already working on it with version 2.0.x but if that wasn't the case here is my log when activating the plugin
```

info: Enabling plugin ytcr
info: Loading plugin "ytcr"...
error: !!!! WARNING !!!!
error: The plugin music_service/ytcr failed to load, setting it to stopped. Error: Error: Cannot find module '/data/plugins/music_service/ytcr/node_modules/yt-cast-receiver/lib/index.js'. Please verify that the package.json has a valid "main" entry
error: Stack trace: Error: Cannot find module '/data/plugins/music_service/ytcr/node_modules/yt-cast-receiver/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:349:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:562:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:917:27)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object. (/data/plugins/music_service/ytcr/dist/index.js:40:41)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at PluginManager.loadCorePlugin (/volumio/app/pluginmanager.js:235:29)
    at Promise._successFn (/volumio/app/pluginmanager.js:1855:19)
    at nextTickCallback (/volumio/node_modules/kew/kew.js:47:28)
error: !!!! WARNING !!!!
info: Done.
```

unfortunately the version 2.0.x is not available in the plugin manager for me.

**Comment by patrickkfkan** [comment]
v1.2.0 is the latest version for current Volumio. v2.x is the version for Bookworm-based Volumio which is in development.

So install v1.2.0 from beta channel of plugin store and restart.

https://community.volumio.com/t/plugin-youtube-cast-receiver/46522/317?u=patrickkfkan
